name: Xiaomi HyperOS - lahaina
on:
  workflow_dispatch:
    inputs:
      build_matrix:
        description: "构建阵列，以英文逗号分隔，预置all"
        type: string
        default: "all"
        required: true
      URL:
        description: "移植包的下载地址"
        required: true
        type: string
      custom_version:
        description: "自定义版本号"
        required: true
        type: string
      OneDrive:
        description: "OneDrive"
        required: true
        type: boolean
        default: true
      GithubRelease:
        description: "Github Release"
        required: true
        type: boolean
        default: false
      pack_type:
        description: "打包Payload.bin"
        required: true
        type: boolean
        default: true
jobs:
  build_matrix:
    name: 设置构建阵列
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: 设置构建阵列
        id: set-matrix
        run: |
          input_var="${{ github.event.inputs.build_matrix }}"
          if [ "$input_var" = "all" ]; then
            input_var="venus,star,haydn"
          fi
          IFS=',' read -ra devices <<< "$input_var"
          json_output="{\"list\":["
          for device in "${devices[@]}"; do
            json_output+="{\"device\":\"$device\"},"
          done
          json_output=${json_output%,}
          json_output+="]}"
          echo "matrix=$json_output" >> $GITHUB_OUTPUT
  removeRelease:
    if: github.event.inputs.GithubRelease == 'true'
    name: 删除 ${{ inputs.custom_version }} 的 Github Release
    runs-on: ubuntu-latest
    steps:
      - name: 删除 ${{ inputs.custom_version }} 的 Github Release
        uses: ncipollo/release-action@main
        with:
          owner: Human-Machine-Matrix
          repo: action_build_lahaina_system
          name: "${{ inputs.custom_version }}"
          tag: "${{ inputs.custom_version }}"
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.GH_TOKEN }}
  build:
    name: 自动构建
    runs-on: ubuntu-latest
    needs: build_matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build_matrix.outputs.matrix) }}
    steps:
      - name: 精简无用组件
        run: |
          docker rmi `docker images -q` || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* || true
          sudo apt -y autoremove --purge || true
          sudo apt -y autoclean || true
          sudo apt clean || true
      - name: 最大化并挂载构建空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 6144
          remove-dotnet: "true"
          temp-reserve-mb: 1024
          remove-android: "true"
          remove-haskell: "true"
      - name: 检出仓库文件
        uses: actions/checkout@v4.2.2
        with:
          repository: Human-Machine-Matrix/action_build_lahaina_system
          ref: main
          token: ${{ secrets.GH_TOKEN }}
      - name: 下载系统包
        run: |
          eval $(cat build_local_HyperOS.sh | grep "apt-get")
          sudo bash "$GITHUB_WORKSPACE"/tools/install_rclone.sh ${{ secrets.GH_TOKEN }}
          mkdir -p ~/.config/rclone/
          unzip -o -q -P ${{ secrets.PASSWORD }} "$GITHUB_WORKSPACE"/tools/rclone_config.zip -d ~/.config/rclone/
          device=$(echo "$MATRIX_CONTEXT" | jq -r '.list.device')
          echo "device=$device" >> "$GITHUB_ENV"
          model=$(echo "$custom_version" | cut -d"." -f5 | sed 's/^.\(..\).*$/\1/')
          if [[ "$device" == "star" ]]; then
            date=${custom_version//${model}/KA}
            ORIGIN_URL=https://hugeota.d.miui.com/OS1.0.8.0.UKACNXM/miui_STAR_OS1.0.8.0.UKACNXM_e0ee8bc158_14.0.zip
          elif [[ "$device" == "venus" ]]; then
            date=${custom_version//${model}/KB}
            ORIGIN_URL=https://hugeota.d.miui.com/OS1.0.10.0.UKBCNXM/miui_VENUS_OS1.0.10.0.UKBCNXM_dd85ac3249_14.0.zip
          elif [[ "$device" == "haydn" ]]; then
            date=${custom_version//${model}/KK}
            ORIGIN_URL=https://hugeota.d.miui.com/OS1.0.8.0.UKKCNXM/miui_HAYDN_OS1.0.8.0.UKKCNXM_1ec17c8a90_14.0.zip
          fi
          echo "date=$date" >> "$GITHUB_ENV"
          ORIGIN_ZIP_NAME=$(echo "$ORIGIN_URL" | cut -d"?" -f1 | cut -d"/" -f5) 
          TARGET_ZIP_NAME=$(echo "$URL" | cut -d"?" -f1 | cut -d"/" -f5)
          rclone copy -P OneDrive:/MI_Packages/RubbishBin/BottomPackages/"$ORIGIN_ZIP_NAME" "$GITHUB_WORKSPACE"
          if [[ "$URL" == *PrePackages* ]]; then
            rclone copy -P OneDrive:/MI_Packages/RubbishBin/PrePackages/"$TARGET_ZIP_NAME" "$GITHUB_WORKSPACE"
          elif [[ "$URL" != "$ORIGIN_URL" ]]; then
            aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" "$URL"
          fi
          if [[ "$pack_type" == "true" ]]; then
            if [[ "$device" == "star" ]]; then
              rclone copy -P OneDrive:/MI_Packages/RubbishBin/PreArtifacts/star.txt "$GITHUB_WORKSPACE"
              dos2unix "$GITHUB_WORKSPACE"/star.txt
              post_package=$(cat "$GITHUB_WORKSPACE"/star.txt)
            elif [[ "$device" == "venus" ]]; then
              rclone copy -P OneDrive:/MI_Packages/RubbishBin/PreArtifacts/venus.txt "$GITHUB_WORKSPACE"
              dos2unix "$GITHUB_WORKSPACE"/venus.txt
              post_package=$(cat "$GITHUB_WORKSPACE"/venus.txt)
            elif [[ "$device" == "haydn" ]]; then
              rclone copy -P OneDrive:/MI_Packages/RubbishBin/PreArtifacts/haydn.txt "$GITHUB_WORKSPACE"
              dos2unix "$GITHUB_WORKSPACE"/haydn.txt
              post_package=$(cat "$GITHUB_WORKSPACE"/haydn.txt)
            fi
            echo "post_package=$post_package" >> $GITHUB_ENV
          fi
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          custom_version: ${{ inputs.custom_version }}
          URL: ${{ inputs.URL }}
          pack_type: ${{ inputs.pack_type }}
      - if: github.event.inputs.pack_type == 'true'
        name: 下载 ${{ env.post_package }} 
        run: |
          if [[ -n "$post_package" ]]; then
            rclone copy -P OneDrive:/MI_Packages/RubbishBin/PreArtifacts/"$post_package" "$GITHUB_WORKSPACE"/tools/payload_repack
          fi
      - name: 下载 TWRP
        uses: robinraju/release-downloader@v1.9
        with:
            repository: zjw2017/TWRP_Backup
            tag: "twrp"
            fileName: "*${{ env.device }}*"
            out-file-path: "${{ env.device }}_files"
            token: ${{ secrets.GH_TOKEN }}
      - name: 自动构建
        run: |
          sudo appToken="${{ secrets.appToken }}" TMPDIR="$GITHUB_WORKSPACE"/TMPDIR user=$(whoami) bash build_local_HyperOS.sh $URL $device $date $pack_type "$post_package"
          cat "$GITHUB_WORKSPACE"/PackageInfo.txt >> $GITHUB_ENV
        env:
          URL: ${{ inputs.URL }}
          pack_type: ${{ inputs.pack_type }}
      - if: github.event.inputs.GithubRelease == 'true'
        name: 处理包
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/GithubRelease
          cd "$GITHUB_WORKSPACE"/GithubRelease
          sudo split -b 1536M -d "$GITHUB_WORKSPACE"/zip/"$NEW_PACKAGE_NAME" "$NEW_PACKAGE_NAME"
          cd "$GITHUB_WORKSPACE"
          touch file.log
          echo "$NEW_PACKAGE_NAME" > file.log
      - if: github.event.inputs.GithubRelease == 'true'
        name: 上传到Github Release
        uses: ncipollo/release-action@main
        with:
          owner: Human-Machine-Matrix
          repo: action_build_lahaina_system
          artifacts: ${{ github.workspace }}/GithubRelease/*
          name: "${{ inputs.custom_version }}"
          tag: "${{ inputs.custom_version }}"
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          token: ${{ secrets.GH_TOKEN }}
      - if: ${{ github.event.inputs.OneDrive == 'true' }}
        name: 上传到OneDrive
        run: |
          rclone mkdir OneDrive:/MI_Packages/RubbishBin/DevPackages
          for i in $(ls "$GITHUB_WORKSPACE"/zip); do
            if [[ "$i" == "$bottom_package_name" ]]; then
              rclone copy -P ./zip/$i OneDrive:/MI_Packages/RubbishBin/PreArtifacts --buffer-size=1024M
            else
              rclone copy -P ./zip/$i OneDrive:/MI_Packages/RubbishBin/DevPackages --buffer-size=1024M
            fi
          done
      - name: 发送 Onedrive 上传成功通知
        run: |
          if [[ "$device" == "star" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken }}","title":"Xiaomi 11 Pro/Ultra '"$date"'已构建完成","content":" **Xiaomi 11 Pro/Ultra '"$date"'已构建完成** \n \n **底包的 OS 版本：'"$bottom_os_date"'** \n \n **底包的 Android 安全更新版本：'"$bottom_security_patch"'** \n \n **底包的 Android 基线版本：'"$bottom_base_line"'** \n \n **移植包的 OS 版本：'"$target_os_date"'** \n \n **移植包的 Android 安全更新版本：'"$target_security_patch"'** \n \n **移植包的 Android 基线版本：'"$target_base_line"'** \n \n **包名：'"$NEW_PACKAGE_NAME"'** \n \n **MD5：'"$MD5"'** \n \n **下载地址为：[https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"'](https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"')** ","topic":"lahaina","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "venus" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken }}","title":"Xiaomi 11 '"$date"'已构建完成","content":" **Xiaomi 11 '"$date"'已构建完成** \n \n **底包的 OS 版本：'"$bottom_os_date"'** \n \n **底包的 Android 安全更新版本：'"$bottom_security_patch"'** \n \n **底包的 Android 基线版本：'"$bottom_base_line"'** \n \n **移植包的 OS 版本：'"$target_os_date"'** \n \n **移植包的 Android 安全更新版本：'"$target_security_patch"'** \n \n **移植包的 Android 基线版本：'"$target_base_line"'** \n \n **包名：'"$NEW_PACKAGE_NAME"'** \n \n **MD5：'"$MD5"'** \n \n **下载地址为：[https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"'](https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"')** ","topic":"lahaina","template":"markdown"}' http://www.pushplus.plus/send || true
          elif [[ "$device" == "haydn" ]]; then
            curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{ secrets.appToken }}","title":"Redmi K40 Pro/Pro+ '"$date"'已构建完成","content":" **Redmi K40 Pro/Pro+ '"$date"'已构建完成** \n \n **底包的 OS 版本：'"$bottom_os_date"'** \n \n **底包的 Android 安全更新版本：'"$bottom_security_patch"'** \n \n **底包的 Android 基线版本：'"$bottom_base_line"'** \n \n **移植包的 OS 版本：'"$target_os_date"'** \n \n **移植包的 Android 安全更新版本：'"$target_security_patch"'** \n \n **移植包的 Android 基线版本：'"$target_base_line"'** \n \n **包名：'"$NEW_PACKAGE_NAME"'** \n \n **MD5：'"$MD5"'** \n \n **下载地址为：[https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"'](https://onedrive.zjw.js.cn/RubbishBin/DevPackages/'"$NEW_PACKAGE_NAME"')** ","topic":"lahaina","template":"markdown"}' http://www.pushplus.plus/send || true
          fi
